config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    :omniauth_callbacks => "omniauth_callbacks" 
  }
  
  resources :tls

  post '/users/edit/profile' => 'users#edit_profile', as: 'profile_edit'

  root 'users#home'

end

app/models/channel_twitter.rb
class ChannelTwitter < ActiveRecord::Base
end

app/models/tl.rb
class Tl < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable, omniauth_providers: [:twitter]
  def self.from_omniauth(auth)
    where(provider: auth["provider"], uid: auth["uid"]).first_or_create do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.username = auth["info"]["nickname"]
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

#ログアウト後のリダイレクトをログアウト前のページにする場合
def after_sign_out_path_for(resource)
   new_user_session_path
end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @user = User.from_omniauth(request.env["omniauth.auth"]).except("extra")
    if @user.persisted?
      flash.notice = "ログインしました！"
      sign_in_and_redirect @user
    else
      session["devise.user_attributes"] = @user.attributes
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/tls_controller.rb
class TlsController < ApplicationController
  
  def index
    if user_signed_in?
      @tl = Tl.all
      @user = current_user
    else
      redirect_to 'users/home' 
    end
  end

  def new
    @user = current_user
    @tl = Tl.new
  end

  def create
    @tl = Tl.new
    @tl[:text] = params[:tl][:text]
    @tl[:user_id] = current_user[:id]
    if @tl.save
      redirect_to root_path
    else
      redirect_to new_tl_path
    end
  end

  def show
  end

  def destroy
  end

  def update
  end

  def edit
  end
end

=begin
end
<!--<header>
        <nav>
            <% if user_signed_in? %>
                <strong<%= link_to current_user.username, controller: 'users', action: 'show'  %></strong>
                <%= link_to 'プロフィール変更', edit_user_registration_path %>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
            <% else %>
                <%= link_to 'サインアップ', new_user_registration_path %>
                <%= link_to 'ログイン', new_user_session_path %>
            <% end %>
        </nav>
</header>
-->

=end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    super
    @user = current_user
  end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def home
    if user_signed_in?
  	  @user = current_user
      @tl = Tl.where(user_id: current_user[:id])
      @tweet_sum = @tl.count
    else
      redirect_to '/users/sign_in'
    end
  end
  
  def show

  end

  def edit_profile
  	if user_signed_in?
  	  redirect_to 'users/home'
  	else
  	  render text: 'test'
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/tls_helper.rb
module TlsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PjSlatter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_headerber.html.erb
<%= stylesheet_link_tag "shared/headerber", :media => "all" %>

<div id="headerbar_">
  <div id="titlerogo_">Slatter</div>
  <div id="headerbar_link_">ＨＯＭＥ　<%= link_to 'Ｔｌ', tls_path %></div>
</div>

app/views/shared/_tlber.html.erb
<% @tl.each do |tl| %>
  <ul>
    <li>
      <div id="_tweet">
  	    <div id="_top">画像　<%= @user[:username] %>　<%= link_to 'お気に入り' %>(<%= tl.sum_fav %>)　<%= link_to 'ピックアップ' %>(<%= tl.sum_pick %>)</div>
        <div id="_main"><%= tl.text %></div>
      </div>
    </li>
  </ul>
<% end %>

app/views/tls/create.html.erb
<h1>Tls#create</h1>
<p>Find me in app/views/tls/create.html.erb</p>

app/views/tls/destroy.html.erb
<h1>Tls#destroy</h1>
<p>Find me in app/views/tls/destroy.html.erb</p>

app/views/tls/edit.html.erb
<h1>Tls#edit</h1>
<p>Find me in app/views/tls/edit.html.erb</p>

app/views/tls/index.html.erb
<%= render 'shared/tlber'  %>

app/views/tls/new.html.erb
<%= stylesheet_link_tag 'tl/new' %>

<%= render 'shared/headerber' %>
<div id="main">
  <div id="form_area">
    <%= form_for @tl, html: {id: 'form_tweet'} do |f| %>
  	  <div id="form_top">
  	    画像<%= @user[:username]%>　お気に入り(0)　ピックアップ(0)
      </div>
      <div id="form_text">
        <%= f.text_area :text, cols: 55, rows: 15 %>
  	  </div>
  	  <%= f.submit 'ついーと' %>
    <% end %>
  </div>
</div>

app/views/tls/show.html.erb
<h1>Tls#show</h1>
<p>Find me in app/views/tls/show.html.erb</p>

app/views/tls/update.html.erb
<h1>Tls#update</h1>
<p>Find me in app/views/tls/update.html.erb</p>

app/views/users/edit_profile.html.erb
test

app/views/users/home.html.erb
  <%= stylesheet_link_tag "user/home", :media => "all" %>
    
    <%= render 'shared/headerber' %>

    <div id="header">
      <div id="profile">
        <div id="profile_left">
          <div id="profile_image"><%= image_tag("home/main_bgi01.jpg") %></div>
       　  <div id="profile_username"><%= @user[:username] %></div>
          <div id="profile_edit"><%= link_to 'edit', edit_user_registration_path %></div>
          <div id="profile_info">
            フォロー：<%= @user[:followNum] %><br>
            フォロワー：<%= @user[:followerNum] %><br>
            ツイート数：<%= @tweet_sum %>
          </div>
        </div>
        <div id="profile_link"><%= link_to 'logout', destroy_user_session_path, method: :delete %></div>
        <div id="profile_text"><%= @user[:myText] %></div>
      </div>    
    </div>

    <div id="main">
      <div id="selectbar">
      　　<div id="selectber_link">
          お気に入り(0)　ピックアップ(0)　足跡
        </div>
        <div id="tweet_button"><%= link_to "ツイートする", new_tl_path %><%=image_tag('tl/tweet.jpg') %>
        </div>
      </div>
      <div id="sidebar">
        <ul>
          <li>ひとこと</li>
          <li>Anime</li>
          <li>Movie</li>
          <li>Comic</li>
        </ul>
      </div>
      <div id="tlbar">
        <%= render 'shared/tlber' %>
        <!--% if params[:page_type] = 0 then %>
          %= render @page_type1 %>
        % end %> -->
      </div>
    </div>
    <div id="footer">footer</div>

app/views/users/show.html.erb
show